//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading;
using CBK.Framework.Event;
using CBK.Framework.Utility;

namespace CBK.Logic.UI.{{ package_name }}
{
    [GameFramework.UI.FairyGUI.FairyGUIComponent(URL)]
    public partial class {{ name }} : {{ extension_type.full_name }}
    {
        public const string URL = "{{ url }}";

        #region [子节点]
{{ for node in nodes }} {{ if is_accept_name node.name }}
        public {{ node.ref_type_full_name }} {{ upper_first node.name }};
{{ end }} {{ end }}
        #endregion

        #region [控制器]
{{ for controller in controllers }} {{ if is_accept_name controller.name }}
        public FairyGUI.Controller {{ upper_first controller.name }}Controller;

        public enum {{ upper_first controller.name }}ControllerPage
        { {{ for page in controller.pages }}
            Page{{ upper_first page }},{{ end }}
        }

        public {{ upper_first controller.name }}ControllerPage Current{{ upper_first controller.name }}ControllerPage
        {
            get => ({{ upper_first controller.name }}ControllerPage){{ upper_first controller.name }}Controller.selectedIndex;
            set => {{ upper_first controller.name }}Controller.selectedIndex = (int)value;
        }
{{ end }} {{ end }}
        #endregion

        #region [动效]
{{ for transition in transitions }} {{ if is_accept_name transition.name }}
        public FairyGUI.Transition {{ upper_first transition.name }}Transition;
{{ end }} {{ end }}
        #endregion

        #region [DisposableGroup]

        /// <summary>
        /// 在组件RemoveFromStage时会调用Dispose的DisposableGroup
        /// </summary>
        private DisposableGroup DisposableGroupOnRemoveFromStage => m_DisposableGroupOnRemoveFromStage ??= new DisposableGroup();
        
        /// <summary>
        /// 在组件Dispose时会调用Dispose的DisposableGroup
        /// </summary>
        private DisposableGroup DisposableGroupOnDispose => m_DisposableGroupOnDispose ??= new DisposableGroup();
        
        private DisposableGroup m_DisposableGroupOnRemoveFromStage;
        private DisposableGroup m_DisposableGroupOnDispose;

        #endregion

        #region [CancellationTokenSource]
        
        /// <summary>
        /// 在组件RemoveFromStage时会被取消的令牌
        /// </summary>
        private CancellationToken CancellationTokenOnRemoveFromStage => (m_CancellationTokenSourceOnRemoveFromStage ??= new CancellationTokenSource()).Token;
        
        /// <summary>
        /// 在组件Dispose时会被取消的令牌
        /// </summary>
        private CancellationToken CancellationTokenOnDispose => (m_CancellationTokenSourceOnDispose ??= new CancellationTokenSource()).Token;
        
        private CancellationTokenSource m_CancellationTokenSourceOnRemoveFromStage;
        private CancellationTokenSource m_CancellationTokenSourceOnDispose;

        #endregion
        
        public override void ConstructFromXML(FairyGUI.Utils.XML xml)
        {
            base.ConstructFromXML(xml);

            #region [子节点]
{{ for node in nodes }} {{ if is_accept_name node.name }}
            {{ upper_first node.name }} = ({{ node.ref_type_full_name }})GetChild("{{ node.name }}");
{{ end }} {{ end }}
            #endregion

            #region [控制器]
{{ for controller in controllers }} {{ if is_accept_name controller.name }}
            {{ upper_first controller.name }}Controller = GetController("{{ controller.name }}");
{{ end }} {{ end }}
            #endregion

            #region [动效]
{{ for transition in transitions }} {{ if is_accept_name transition.name }}
            {{ upper_first transition.name }}Transition = GetTransition("{{ transition.name }}");
{{ end }} {{ end }}
            #endregion

            #region [生命周期事件]

            this.onAddedToStage.Add(_OnAddedToStage);
            this.onRemovedFromStage.Add(_OnRemoveFromStage);

            #endregion

            OnInitialize();
        }

        public override void Dispose()
        {
            OnDispose();
            
            if (m_CancellationTokenSourceOnDispose != null)
            {
                m_CancellationTokenSourceOnDispose.Cancel();
                m_CancellationTokenSourceOnDispose.Dispose();
                m_CancellationTokenSourceOnDispose = null;
            }

            if (m_DisposableGroupOnDispose != null)
            {
                m_DisposableGroupOnDispose.Dispose();
            }
            
            base.Dispose();
        }
        
        #region [生命周期]
        
        private void _OnAddedToStage()
        {
            OnAddedToStage();
        }
        
        private void _OnRemoveFromStage()
        {
            OnRemoveFromStage();
            
            if (m_CancellationTokenSourceOnRemoveFromStage != null)
            {
                m_CancellationTokenSourceOnRemoveFromStage.Cancel();
                m_CancellationTokenSourceOnRemoveFromStage.Dispose();
                m_CancellationTokenSourceOnRemoveFromStage = null;
            }
        
            if (m_DisposableGroupOnRemoveFromStage != null)
            {
                m_DisposableGroupOnRemoveFromStage.Dispose();
            }
        }
        
        partial void OnAddedToStage();
        partial void OnRemoveFromStage();
        
        #endregion
        
        #region [EventExtensions]
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在RemoveFromStage阶段自动解除监听
        /// </summary>
        private void AddListenerDisposeOnRemoveFromStage(string eventName, EventHandler handler)
        {
            DisposableGroupOnRemoveFromStage.Add(EventService.That.AddListenerAsDisposable(eventName, handler));
        }
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在RemoveFromStage阶段自动解除监听
        /// </summary>
        private void AddListenerDisposeOnRemoveFromStage<T>(EventHandler handler) where T : EventArgs
        {
            DisposableGroupOnRemoveFromStage.Add(EventService.That.AddListenerAsDisposable<T>(handler));
        }
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在RemoveFromStage阶段自动解除监听
        /// </summary>
        private void SubscribeDisposeOnRemoveFromStage(string eventName, EventHandler handler)
        {
            DisposableGroupOnRemoveFromStage.Add(EventService.That.SubscribeAsDisposable(eventName, handler));
        }
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在RemoveFromStage阶段自动解除监听
        /// </summary>
        private void SubscribeDisposeOnRemoveFromStage<T>(EventHandler handler) where T : EventArgs
        {
            DisposableGroupOnRemoveFromStage.Add(EventService.That.SubscribeAsDisposable<T>(handler));
        }
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在Dispose阶段自动解除监听
        /// </summary>
        private void AddListenerDisposeOnDispose(string eventName, EventHandler handler)
        {
            DisposableGroupOnDispose.Add(EventService.That.AddListenerAsDisposable(eventName, handler));
        }
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在Dispose阶段自动解除监听
        /// </summary>
        private void AddListenerDisposeOnDispose<T>(EventHandler handler) where T : EventArgs
        {
            DisposableGroupOnDispose.Add(EventService.That.AddListenerAsDisposable<T>(handler));
        }
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在Dispose阶段自动解除监听
        /// </summary>
        private void SubscribeDisposeOnDispose(string eventName, EventHandler handler)
        {
            DisposableGroupOnDispose.Add(EventService.That.SubscribeAsDisposable(eventName, handler));
        }
        
        /// <summary>
        /// 通过事件名添加事件监听 它将在Dispose阶段自动解除监听
        /// </summary>
        private void SubscribeDisposeOnDispose<T>(EventHandler handler) where T : EventArgs
        {
            DisposableGroupOnDispose.Add(EventService.That.SubscribeAsDisposable<T>(handler));
        }
        
        #endregion
    }
}