//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBK.Logic.UI.{{ package_name }}
{
    [GameFramework.UI.FairyGUI.FairyGUIForm("{{ package_name }}", nameof({{ name }}))]
    public partial class {{ name }}
    {
        #region [子节点]
{{ for node in nodes }} {{ if is_accept_name node.name }}
        private {{ node.ref_type_full_name }} m_{{ upper_first node.name }};
{{ end }} {{ end }}
        #endregion

        #region [控制器]
{{ for controller in controllers }} {{ if is_accept_name controller.name }}
        private FairyGUI.Controller m_{{ upper_first controller.name }}Controller;

        private enum {{ upper_first controller.name }}ControllerPage
        { {{ for page in controller.pages }}
            Page{{ upper_first page }},{{ end }}
        }

        private {{ upper_first controller.name }}ControllerPage Current{{ upper_first controller.name }}ControllerPage
        {
            get => ({{ upper_first controller.name }}ControllerPage)m_{{ upper_first controller.name }}Controller.selectedIndex;
            set => m_{{ upper_first controller.name }}Controller.selectedIndex = (int)value;
        }
{{ end }} {{ end }}
        #endregion

        #region [动效]
{{ for transition in transitions }}  {{ if is_accept_name transition.name }}
        private FairyGUI.Transition m_{{ upper_first transition.name }}Transition;
{{ end }} {{ end }}
        #endregion
        
        protected override void OnInit(object userData)
        {
            base.OnInit(userData);

            #region [子节点]
{{ for node in nodes }} {{ if is_accept_name node.name }}
            m_{{ upper_first node.name }} = ({{ node.ref_type_full_name }})ContentPane.GetChild("{{ node.name }}");
{{ end }} {{ end }}
            #endregion

            #region [控制器]
{{ for controller in controllers }} {{ if is_accept_name controller.name }}
            m_{{ upper_first controller.name }}Controller = ContentPane.GetController("{{ controller.name }}");
{{ end }} {{ end }}
            #endregion

            #region [动效]
{{ for transition in transitions }} {{ if is_accept_name transition.name }}
            m_{{ upper_first transition.name }}Transition = ContentPane.GetTransition("{{ transition.name }}");
{{ end }} {{ end }}
            #endregion

            OnInitialize(userData);
        }
    }
}